from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from sqlmodel import Session, select
from typing import List, Optional
import json
from dotenv import load_dotenv

load_dotenv()

from .models import engine, create_db_and_tables, User, RouteMap, Node, UserProgress
from .services.claude_service import ClaudeService

app = FastAPI(title="Learning Route Advisor API")

# Setup CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, restrict this
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.on_event("startup")
def on_startup():
    create_db_and_tables()

def get_session():
    with Session(engine) as session:
        yield session

@app.post("/users/", response_model=User)
def create_user(user: User, session: Session = Depends(get_session)):
    session.add(user)
    session.commit()
    session.refresh(user)
    return user

@app.get("/users/{username}", response_model=User)
def get_user(username: str, session: Session = Depends(get_session)):
    statement = select(User).where(User.username == username)
    user = session.exec(statement).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    return user

@app.post("/onboarding/", response_model=RouteMap)
def onboarding(username: str, goal: str, session: Session = Depends(get_session)):
    try:
        # Get user
        statement = select(User).where(User.username == username)
        user = session.exec(statement).first()
        if not user:
            # Auto-create user for demo purposes
            user = User(username=username, password_hash="dummy")
            session.add(user)
            session.commit()
            session.refresh(user)
        
        # Create RouteMap
        route_map = RouteMap(user_id=user.id, goal=goal)
        session.add(route_map)
        session.commit()
        session.refresh(route_map)
        
        # Call Claude to generate nodes
        print(f"DEBUG: Generating learning route for goal: {goal}", flush=True)
        raw_nodes = ClaudeService.generate_learning_route(goal)
        print(f"DEBUG: Raw nodes received from API: {json.dumps(raw_nodes, indent=2)}", flush=True)
        
        if not raw_nodes:
            print("DEBUG WARNING: No nodes were generated by the API!", flush=True)

        # Map title to Node id for hierarchy links
        title_to_node = {}
        
        # First pass: Create all nodes
        for rn in raw_nodes:
            node = Node(
                route_map_id=route_map.id,
                title=rn["title"],
                description=rn["description"],
                level=rn["level"]
            )
            session.add(node)
            session.commit()
            session.refresh(node)
            print(f"DEBUG: Created node: {node.title} (ID: {node.id})", flush=True)
            title_to_node[rn["title"]] = node
        
        # Second pass: Link parents
        for rn in raw_nodes:
            if rn.get("parent_title"):
                child_node = title_to_node.get(rn["title"])
                parent_node = title_to_node.get(rn["parent_title"])
                if child_node and parent_node:
                    child_node.parent_id = parent_node.id
                    session.add(child_node)
        
        session.commit()
        session.refresh(route_map)
        return route_map
    except Exception as e:
        print(f"DEBUG ERROR in onboarding: {str(e)}", flush=True)
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/route-maps/{route_id}/nodes", response_model=List[Node])
def get_route_nodes(route_id: int, session: Session = Depends(get_session)):
    statement = select(Node).where(Node.route_map_id == route_id)
    nodes = session.exec(statement).all()
    return nodes

@app.get("/nodes/{node_id}/resources")
def get_node_resources(node_id: int, session: Session = Depends(get_session)):
    node = session.get(Node, node_id)
    if not node:
        raise HTTPException(status_code=404, detail="Node not found")
    
    if node.resources_json:
        return json.loads(node.resources_json)
    
    # Fetch from Claude
    route_map = session.get(RouteMap, node.route_map_id)
    resources = ClaudeService.get_resources_for_topic(node.title, route_map.goal)
    
    node.resources_json = json.dumps(resources)
    session.add(node)
    session.commit()
    return resources

@app.post("/nodes/{node_id}/toggle-complete")
def toggle_node_complete(node_id: int, username: str, session: Session = Depends(get_session)):
    user_stmt = select(User).where(User.username == username)
    user = session.exec(user_stmt).first()
    
    stmt = select(UserProgress).where(UserProgress.node_id == node_id, UserProgress.user_id == user.id)
    progress = session.exec(stmt).first()
    
    if progress:
        progress.is_completed = not progress.is_completed
    else:
        progress = UserProgress(user_id=user.id, node_id=node_id, is_completed=True)
    
    session.add(progress)
    session.commit()
    return {"status": "success", "is_completed": progress.is_completed}

@app.get("/users/{username}/progress")
def get_user_progress(username: str, session: Session = Depends(get_session)):
    user_stmt = select(User).where(User.username == username)
    user = session.exec(user_stmt).first()
    if not user:
        return []
    
    stmt = select(UserProgress).where(UserProgress.user_id == user.id)
    progress_list = session.exec(stmt).all()
    return {p.node_id: p.is_completed for p in progress_list}
